/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IChangeContract, IChangeContractInterface } from "../../interfaces/IChangeContract.js";

  const _abi = [
  {
    "inputs": [],
    "name": "execute",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IChangeContract__factory {
    static readonly abi = _abi;
    static createInterface(): IChangeContractInterface {
      return new Interface(_abi) as IChangeContractInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IChangeContract {
      return new Contract(address, _abi, runner) as unknown as IChangeContract;
    }
  }
  