/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IGovernor, IGovernorInterface } from "../../interfaces/IGovernor.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "contract IChangeContract",
        "name": "changeContract_",
        "type": "address"
      }
    ],
    "name": "executeChange",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "changer_",
        "type": "address"
      }
    ],
    "name": "isAuthorizedChanger",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IGovernor__factory {
    static readonly abi = _abi;
    static createInterface(): IGovernorInterface {
      return new Interface(_abi) as IGovernorInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IGovernor {
      return new Contract(address, _abi, runner) as unknown as IGovernor;
    }
  }
  