/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IMoC, IMoCInterface } from "../../interfaces/IMoC.js";

  const _abi = [
  {
    "inputs": [],
    "name": "makeUnstoppable",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IMoC__factory {
    static readonly abi = _abi;
    static createInterface(): IMoCInterface {
      return new Interface(_abi) as IMoCInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IMoC {
      return new Contract(address, _abi, runner) as unknown as IMoC;
    }
  }
  