/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IChangeContract__factory } from './IChangeContract__factory.js';
export { IGovernor__factory } from './IGovernor__factory.js';