/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IMoCInrateMinimal, IMoCInrateMinimalInterface } from "../../../../changers/remove_panic_button/RemovePanicButtonProposal.sol/IMoCInrateMinimal.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "newBitProRate",
        "type": "uint256"
      }
    ],
    "name": "setBitProRate",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "txType",
        "type": "uint8"
      },
      {
        "internalType": "uint256",
        "name": "value",
        "type": "uint256"
      }
    ],
    "name": "setCommissionRateByTxType",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IMoCInrateMinimal__factory {
    static readonly abi = _abi;
    static createInterface(): IMoCInrateMinimalInterface {
      return new Interface(_abi) as IMoCInrateMinimalInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IMoCInrateMinimal {
      return new Contract(address, _abi, runner) as unknown as IMoCInrateMinimal;
    }
  }
  