/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IMoCMinimal, IMoCMinimalInterface } from "../../../../changers/remove_panic_button/RemovePanicButtonProposal.sol/IMoCMinimal.js";

  const _abi = [
  {
    "inputs": [],
    "name": "makeUnstoppable",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IMoCMinimal__factory {
    static readonly abi = _abi;
    static createInterface(): IMoCMinimalInterface {
      return new Interface(_abi) as IMoCMinimalInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IMoCMinimal {
      return new Contract(address, _abi, runner) as unknown as IMoCMinimal;
    }
  }
  