[profile.default]
src = "contracts"
test = "contracts/tests"
out = "out"
libs = ["node_modules"]
remappings = [
  "@moc/flow/=node_modules/@moc/flow/",
  "@moc/lending/=node_modules/@moc/lending/",
  "@moc/main/=node_modules/@moc/main/",
  "@moc/moc-main/=node_modules/@moc/moc-main/",
  "@moc/oracles/=node_modules/@moc/oracles/",
  "@moc/periphery/=node_modules/@moc/periphery/",
  "@moc/rbtc/=node_modules/@moc/rbtc/",
  "@moc/roc/=node_modules/@moc/roc/",
  "@openzeppelin/=node_modules/@openzeppelin/",
  "forge-std/=node_modules/forge-std/src/",
  "moc-main-latest/=node_modules/moc-main-latest/",
]
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "london"
fs_permissions = [
  { access = "read", path = "./ignition/modules/BufferPctAndCleanMocV1/parameters" },
  { access = "read", path = "./ignition/modules/LendingAndBorrowingV1/parameters" },
  { access = "read", path = "./ignition/modules/upgrade_votingMachine/parameters" },
]
