/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MoCInrateMock } from './MoCInrateMock.js';
export type { MoCMock } from './MoCMock.js';
export type { MoCv2Mock } from './MoCv2Mock.js';
export type { MockGovernor } from './MockGovernor.js';