/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MoCInrateMockInterface extends Interface {
    getFunction(nameOrSignature: "bitProRate" | "commissionByTxType" | "setBitProRate" | "setCommissionRateByTxType"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BitProRateSet" | "CommissionRateSet"): EventFragment;

    encodeFunctionData(functionFragment: 'bitProRate', values?: undefined): string;
encodeFunctionData(functionFragment: 'commissionByTxType', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setBitProRate', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setCommissionRateByTxType', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'bitProRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'commissionByTxType', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setBitProRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setCommissionRateByTxType', data: BytesLike): Result;
  }

  
    export namespace BitProRateSetEvent {
      export type InputTuple = [newRate: BigNumberish];
      export type OutputTuple = [newRate: bigint];
      export interface OutputObject {newRate: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CommissionRateSetEvent {
      export type InputTuple = [txType: BigNumberish, fee: BigNumberish];
      export type OutputTuple = [txType: bigint, fee: bigint];
      export interface OutputObject {txType: bigint, fee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MoCInrateMock extends BaseContract {
    
    connect(runner?: ContractRunner | null): MoCInrateMock;
    waitForDeployment(): Promise<this>;

    interface: MoCInrateMockInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    bitProRate: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    commissionByTxType: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    setBitProRate: TypedContractMethod<
      [newBitProRate: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setCommissionRateByTxType: TypedContractMethod<
      [txType: BigNumberish, value: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'bitProRate'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'commissionByTxType'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setBitProRate'): TypedContractMethod<
      [newBitProRate: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setCommissionRateByTxType'): TypedContractMethod<
      [txType: BigNumberish, value: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'BitProRateSet'): TypedContractEvent<BitProRateSetEvent.InputTuple, BitProRateSetEvent.OutputTuple, BitProRateSetEvent.OutputObject>;
getEvent(key: 'CommissionRateSet'): TypedContractEvent<CommissionRateSetEvent.InputTuple, CommissionRateSetEvent.OutputTuple, CommissionRateSetEvent.OutputObject>;

    filters: {
      
      'BitProRateSet(uint256)': TypedContractEvent<BitProRateSetEvent.InputTuple, BitProRateSetEvent.OutputTuple, BitProRateSetEvent.OutputObject>;
      BitProRateSet: TypedContractEvent<BitProRateSetEvent.InputTuple, BitProRateSetEvent.OutputTuple, BitProRateSetEvent.OutputObject>;
    

      'CommissionRateSet(uint8,uint256)': TypedContractEvent<CommissionRateSetEvent.InputTuple, CommissionRateSetEvent.OutputTuple, CommissionRateSetEvent.OutputObject>;
      CommissionRateSet: TypedContractEvent<CommissionRateSetEvent.InputTuple, CommissionRateSetEvent.OutputTuple, CommissionRateSetEvent.OutputObject>;
    
    };
  }