/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MockGovernorInterface extends Interface {
    getFunction(nameOrSignature: "authorized" | "isAuthorized" | "isAuthorizedChanger" | "setAuthorized"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'authorized', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isAuthorized', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isAuthorizedChanger', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setAuthorized', values: [AddressLike, boolean]): string;

    decodeFunctionResult(functionFragment: 'authorized', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isAuthorized', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isAuthorizedChanger', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAuthorized', data: BytesLike): Result;
  }

  

  export interface MockGovernor extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockGovernor;
    waitForDeployment(): Promise<this>;

    interface: MockGovernorInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    authorized: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isAuthorized: TypedContractMethod<
      [changer: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isAuthorizedChanger: TypedContractMethod<
      [changer: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    setAuthorized: TypedContractMethod<
      [changer: AddressLike, isAuth: boolean, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'authorized'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isAuthorized'): TypedContractMethod<
      [changer: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isAuthorizedChanger'): TypedContractMethod<
      [changer: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'setAuthorized'): TypedContractMethod<
      [changer: AddressLike, isAuth: boolean, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }