/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MoCMockInterface extends Interface {
    getFunction(nameOrSignature: "makeUnstoppable" | "unstoppable"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "MadeUnstoppable"): EventFragment;

    encodeFunctionData(functionFragment: 'makeUnstoppable', values?: undefined): string;
encodeFunctionData(functionFragment: 'unstoppable', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'makeUnstoppable', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unstoppable', data: BytesLike): Result;
  }

  
    export namespace MadeUnstoppableEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MoCMock extends BaseContract {
    
    connect(runner?: ContractRunner | null): MoCMock;
    waitForDeployment(): Promise<this>;

    interface: MoCMockInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    makeUnstoppable: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    unstoppable: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'makeUnstoppable'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unstoppable'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;

    getEvent(key: 'MadeUnstoppable'): TypedContractEvent<MadeUnstoppableEvent.InputTuple, MadeUnstoppableEvent.OutputTuple, MadeUnstoppableEvent.OutputObject>;

    filters: {
      
      'MadeUnstoppable()': TypedContractEvent<MadeUnstoppableEvent.InputTuple, MadeUnstoppableEvent.OutputTuple, MadeUnstoppableEvent.OutputObject>;
      MadeUnstoppable: TypedContractEvent<MadeUnstoppableEvent.InputTuple, MadeUnstoppableEvent.OutputTuple, MadeUnstoppableEvent.OutputObject>;
    
    };
  }