/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MoCv2MockInterface extends Interface {
    getFunction(nameOrSignature: "feeTokenPct" | "mintTCandTPFee" | "redeemTCandTPFee" | "setFeeTokenPct" | "setMintTCandTPFee" | "setRedeemTCandTPFee" | "setSwapTCforTPFee" | "setSwapTPforTCFee" | "setSwapTPforTPFee" | "setTCInterestRate" | "setTcMintFee" | "setTcRedeemFee" | "swapTCforTPFee" | "swapTPforTCFee" | "swapTPforTPFee" | "tcInterestRate" | "tcMintFee" | "tcRedeemFee"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FeeTokenPctSet" | "MintTCandTPFeeSet" | "RedeemTCandTPFeeSet" | "SwapTCforTPFeeSet" | "SwapTPforTCFeeSet" | "SwapTPforTPFeeSet" | "TCInterestRateSet" | "TcMintFeeSet" | "TcRedeemFeeSet"): EventFragment;

    encodeFunctionData(functionFragment: 'feeTokenPct', values?: undefined): string;
encodeFunctionData(functionFragment: 'mintTCandTPFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'redeemTCandTPFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'setFeeTokenPct', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setMintTCandTPFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setRedeemTCandTPFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setSwapTCforTPFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setSwapTPforTCFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setSwapTPforTPFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTCInterestRate', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTcMintFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTcRedeemFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'swapTCforTPFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'swapTPforTCFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'swapTPforTPFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'tcInterestRate', values?: undefined): string;
encodeFunctionData(functionFragment: 'tcMintFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'tcRedeemFee', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'feeTokenPct', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintTCandTPFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'redeemTCandTPFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFeeTokenPct', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMintTCandTPFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRedeemTCandTPFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setSwapTCforTPFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setSwapTPforTCFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setSwapTPforTPFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTCInterestRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTcMintFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTcRedeemFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapTCforTPFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapTPforTCFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapTPforTPFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tcInterestRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tcMintFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tcRedeemFee', data: BytesLike): Result;
  }

  
    export namespace FeeTokenPctSetEvent {
      export type InputTuple = [value: BigNumberish];
      export type OutputTuple = [value: bigint];
      export interface OutputObject {value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MintTCandTPFeeSetEvent {
      export type InputTuple = [value: BigNumberish];
      export type OutputTuple = [value: bigint];
      export interface OutputObject {value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RedeemTCandTPFeeSetEvent {
      export type InputTuple = [value: BigNumberish];
      export type OutputTuple = [value: bigint];
      export interface OutputObject {value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SwapTCforTPFeeSetEvent {
      export type InputTuple = [value: BigNumberish];
      export type OutputTuple = [value: bigint];
      export interface OutputObject {value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SwapTPforTCFeeSetEvent {
      export type InputTuple = [value: BigNumberish];
      export type OutputTuple = [value: bigint];
      export interface OutputObject {value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SwapTPforTPFeeSetEvent {
      export type InputTuple = [value: BigNumberish];
      export type OutputTuple = [value: bigint];
      export interface OutputObject {value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TCInterestRateSetEvent {
      export type InputTuple = [newRate: BigNumberish];
      export type OutputTuple = [newRate: bigint];
      export interface OutputObject {newRate: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TcMintFeeSetEvent {
      export type InputTuple = [value: BigNumberish];
      export type OutputTuple = [value: bigint];
      export interface OutputObject {value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TcRedeemFeeSetEvent {
      export type InputTuple = [value: BigNumberish];
      export type OutputTuple = [value: bigint];
      export interface OutputObject {value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MoCv2Mock extends BaseContract {
    
    connect(runner?: ContractRunner | null): MoCv2Mock;
    waitForDeployment(): Promise<this>;

    interface: MoCv2MockInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    feeTokenPct: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    mintTCandTPFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    redeemTCandTPFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    setFeeTokenPct: TypedContractMethod<
      [feeTokenPct_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setMintTCandTPFee: TypedContractMethod<
      [mintTCandTPFee_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setRedeemTCandTPFee: TypedContractMethod<
      [redeemTCandTPFee_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setSwapTCforTPFee: TypedContractMethod<
      [swapTCforTPFee_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setSwapTPforTCFee: TypedContractMethod<
      [swapTPforTCFee_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setSwapTPforTPFee: TypedContractMethod<
      [swapTPforTPFee_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setTCInterestRate: TypedContractMethod<
      [tcInterestRate_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setTcMintFee: TypedContractMethod<
      [tcMintFee_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setTcRedeemFee: TypedContractMethod<
      [tcRedeemFee_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    swapTCforTPFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    swapTPforTCFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    swapTPforTPFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    tcInterestRate: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    tcMintFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    tcRedeemFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'feeTokenPct'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'mintTCandTPFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'redeemTCandTPFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setFeeTokenPct'): TypedContractMethod<
      [feeTokenPct_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMintTCandTPFee'): TypedContractMethod<
      [mintTCandTPFee_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setRedeemTCandTPFee'): TypedContractMethod<
      [redeemTCandTPFee_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setSwapTCforTPFee'): TypedContractMethod<
      [swapTCforTPFee_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setSwapTPforTCFee'): TypedContractMethod<
      [swapTPforTCFee_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setSwapTPforTPFee'): TypedContractMethod<
      [swapTPforTPFee_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTCInterestRate'): TypedContractMethod<
      [tcInterestRate_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTcMintFee'): TypedContractMethod<
      [tcMintFee_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTcRedeemFee'): TypedContractMethod<
      [tcRedeemFee_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'swapTCforTPFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'swapTPforTCFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'swapTPforTPFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tcInterestRate'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tcMintFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tcRedeemFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'FeeTokenPctSet'): TypedContractEvent<FeeTokenPctSetEvent.InputTuple, FeeTokenPctSetEvent.OutputTuple, FeeTokenPctSetEvent.OutputObject>;
getEvent(key: 'MintTCandTPFeeSet'): TypedContractEvent<MintTCandTPFeeSetEvent.InputTuple, MintTCandTPFeeSetEvent.OutputTuple, MintTCandTPFeeSetEvent.OutputObject>;
getEvent(key: 'RedeemTCandTPFeeSet'): TypedContractEvent<RedeemTCandTPFeeSetEvent.InputTuple, RedeemTCandTPFeeSetEvent.OutputTuple, RedeemTCandTPFeeSetEvent.OutputObject>;
getEvent(key: 'SwapTCforTPFeeSet'): TypedContractEvent<SwapTCforTPFeeSetEvent.InputTuple, SwapTCforTPFeeSetEvent.OutputTuple, SwapTCforTPFeeSetEvent.OutputObject>;
getEvent(key: 'SwapTPforTCFeeSet'): TypedContractEvent<SwapTPforTCFeeSetEvent.InputTuple, SwapTPforTCFeeSetEvent.OutputTuple, SwapTPforTCFeeSetEvent.OutputObject>;
getEvent(key: 'SwapTPforTPFeeSet'): TypedContractEvent<SwapTPforTPFeeSetEvent.InputTuple, SwapTPforTPFeeSetEvent.OutputTuple, SwapTPforTPFeeSetEvent.OutputObject>;
getEvent(key: 'TCInterestRateSet'): TypedContractEvent<TCInterestRateSetEvent.InputTuple, TCInterestRateSetEvent.OutputTuple, TCInterestRateSetEvent.OutputObject>;
getEvent(key: 'TcMintFeeSet'): TypedContractEvent<TcMintFeeSetEvent.InputTuple, TcMintFeeSetEvent.OutputTuple, TcMintFeeSetEvent.OutputObject>;
getEvent(key: 'TcRedeemFeeSet'): TypedContractEvent<TcRedeemFeeSetEvent.InputTuple, TcRedeemFeeSetEvent.OutputTuple, TcRedeemFeeSetEvent.OutputObject>;

    filters: {
      
      'FeeTokenPctSet(uint256)': TypedContractEvent<FeeTokenPctSetEvent.InputTuple, FeeTokenPctSetEvent.OutputTuple, FeeTokenPctSetEvent.OutputObject>;
      FeeTokenPctSet: TypedContractEvent<FeeTokenPctSetEvent.InputTuple, FeeTokenPctSetEvent.OutputTuple, FeeTokenPctSetEvent.OutputObject>;
    

      'MintTCandTPFeeSet(uint256)': TypedContractEvent<MintTCandTPFeeSetEvent.InputTuple, MintTCandTPFeeSetEvent.OutputTuple, MintTCandTPFeeSetEvent.OutputObject>;
      MintTCandTPFeeSet: TypedContractEvent<MintTCandTPFeeSetEvent.InputTuple, MintTCandTPFeeSetEvent.OutputTuple, MintTCandTPFeeSetEvent.OutputObject>;
    

      'RedeemTCandTPFeeSet(uint256)': TypedContractEvent<RedeemTCandTPFeeSetEvent.InputTuple, RedeemTCandTPFeeSetEvent.OutputTuple, RedeemTCandTPFeeSetEvent.OutputObject>;
      RedeemTCandTPFeeSet: TypedContractEvent<RedeemTCandTPFeeSetEvent.InputTuple, RedeemTCandTPFeeSetEvent.OutputTuple, RedeemTCandTPFeeSetEvent.OutputObject>;
    

      'SwapTCforTPFeeSet(uint256)': TypedContractEvent<SwapTCforTPFeeSetEvent.InputTuple, SwapTCforTPFeeSetEvent.OutputTuple, SwapTCforTPFeeSetEvent.OutputObject>;
      SwapTCforTPFeeSet: TypedContractEvent<SwapTCforTPFeeSetEvent.InputTuple, SwapTCforTPFeeSetEvent.OutputTuple, SwapTCforTPFeeSetEvent.OutputObject>;
    

      'SwapTPforTCFeeSet(uint256)': TypedContractEvent<SwapTPforTCFeeSetEvent.InputTuple, SwapTPforTCFeeSetEvent.OutputTuple, SwapTPforTCFeeSetEvent.OutputObject>;
      SwapTPforTCFeeSet: TypedContractEvent<SwapTPforTCFeeSetEvent.InputTuple, SwapTPforTCFeeSetEvent.OutputTuple, SwapTPforTCFeeSetEvent.OutputObject>;
    

      'SwapTPforTPFeeSet(uint256)': TypedContractEvent<SwapTPforTPFeeSetEvent.InputTuple, SwapTPforTPFeeSetEvent.OutputTuple, SwapTPforTPFeeSetEvent.OutputObject>;
      SwapTPforTPFeeSet: TypedContractEvent<SwapTPforTPFeeSetEvent.InputTuple, SwapTPforTPFeeSetEvent.OutputTuple, SwapTPforTPFeeSetEvent.OutputObject>;
    

      'TCInterestRateSet(uint256)': TypedContractEvent<TCInterestRateSetEvent.InputTuple, TCInterestRateSetEvent.OutputTuple, TCInterestRateSetEvent.OutputObject>;
      TCInterestRateSet: TypedContractEvent<TCInterestRateSetEvent.InputTuple, TCInterestRateSetEvent.OutputTuple, TCInterestRateSetEvent.OutputObject>;
    

      'TcMintFeeSet(uint256)': TypedContractEvent<TcMintFeeSetEvent.InputTuple, TcMintFeeSetEvent.OutputTuple, TcMintFeeSetEvent.OutputObject>;
      TcMintFeeSet: TypedContractEvent<TcMintFeeSetEvent.InputTuple, TcMintFeeSetEvent.OutputTuple, TcMintFeeSetEvent.OutputObject>;
    

      'TcRedeemFeeSet(uint256)': TypedContractEvent<TcRedeemFeeSetEvent.InputTuple, TcRedeemFeeSetEvent.OutputTuple, TcRedeemFeeSetEvent.OutputObject>;
      TcRedeemFeeSet: TypedContractEvent<TcRedeemFeeSetEvent.InputTuple, TcRedeemFeeSetEvent.OutputTuple, TcRedeemFeeSetEvent.OutputObject>;
    
    };
  }