/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../common.js"
  
export declare namespace FeesAndBitprorateProposal {
      
    export type CommissionRatesStruct = {txType: BigNumberish, fee: BigNumberish}

    export type CommissionRatesStructOutput = [txType: bigint, fee: bigint] & {txType: bigint, fee: bigint }
  
    }

  export interface FeesAndBitprorateProposalInterface extends Interface {
    getFunction(nameOrSignature: "COMMISSION_RATES_ARRAY_MAX_LENGTH" | "bitProRate" | "commissionRates" | "commissionRatesLength" | "execute" | "mocInrate"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BitProRateSet" | "CommissionRateSet" | "ExecutedOnce"): EventFragment;

    encodeFunctionData(functionFragment: 'COMMISSION_RATES_ARRAY_MAX_LENGTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'bitProRate', values?: undefined): string;
encodeFunctionData(functionFragment: 'commissionRates', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'commissionRatesLength', values?: undefined): string;
encodeFunctionData(functionFragment: 'execute', values?: undefined): string;
encodeFunctionData(functionFragment: 'mocInrate', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'COMMISSION_RATES_ARRAY_MAX_LENGTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bitProRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'commissionRates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'commissionRatesLength', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'execute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mocInrate', data: BytesLike): Result;
  }

  
    export namespace BitProRateSetEvent {
      export type InputTuple = [newRate: BigNumberish];
      export type OutputTuple = [newRate: bigint];
      export interface OutputObject {newRate: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CommissionRateSetEvent {
      export type InputTuple = [txType: BigNumberish, fee: BigNumberish];
      export type OutputTuple = [txType: bigint, fee: bigint];
      export interface OutputObject {txType: bigint, fee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ExecutedOnceEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface FeesAndBitprorateProposal extends BaseContract {
    
    connect(runner?: ContractRunner | null): FeesAndBitprorateProposal;
    waitForDeployment(): Promise<this>;

    interface: FeesAndBitprorateProposalInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    COMMISSION_RATES_ARRAY_MAX_LENGTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    bitProRate: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    commissionRates: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint] & {txType: bigint, fee: bigint }],
      'view'
    >
    

    
    commissionRatesLength: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    execute: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    mocInrate: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'COMMISSION_RATES_ARRAY_MAX_LENGTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'bitProRate'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'commissionRates'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint] & {txType: bigint, fee: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'commissionRatesLength'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'execute'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'mocInrate'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'BitProRateSet'): TypedContractEvent<BitProRateSetEvent.InputTuple, BitProRateSetEvent.OutputTuple, BitProRateSetEvent.OutputObject>;
getEvent(key: 'CommissionRateSet'): TypedContractEvent<CommissionRateSetEvent.InputTuple, CommissionRateSetEvent.OutputTuple, CommissionRateSetEvent.OutputObject>;
getEvent(key: 'ExecutedOnce'): TypedContractEvent<ExecutedOnceEvent.InputTuple, ExecutedOnceEvent.OutputTuple, ExecutedOnceEvent.OutputObject>;

    filters: {
      
      'BitProRateSet(uint256)': TypedContractEvent<BitProRateSetEvent.InputTuple, BitProRateSetEvent.OutputTuple, BitProRateSetEvent.OutputObject>;
      BitProRateSet: TypedContractEvent<BitProRateSetEvent.InputTuple, BitProRateSetEvent.OutputTuple, BitProRateSetEvent.OutputObject>;
    

      'CommissionRateSet(uint8,uint256)': TypedContractEvent<CommissionRateSetEvent.InputTuple, CommissionRateSetEvent.OutputTuple, CommissionRateSetEvent.OutputObject>;
      CommissionRateSet: TypedContractEvent<CommissionRateSetEvent.InputTuple, CommissionRateSetEvent.OutputTuple, CommissionRateSetEvent.OutputObject>;
    

      'ExecutedOnce()': TypedContractEvent<ExecutedOnceEvent.InputTuple, ExecutedOnceEvent.OutputTuple, ExecutedOnceEvent.OutputObject>;
      ExecutedOnce: TypedContractEvent<ExecutedOnceEvent.InputTuple, ExecutedOnceEvent.OutputTuple, ExecutedOnceEvent.OutputObject>;
    
    };
  }