/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, AddressLike, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../common.js"
  import type { RemovePanicButtonProposal, RemovePanicButtonProposalInterface } from "../../../changers/remove_panic_button/RemovePanicButtonProposal.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "contract IMoC",
        "name": "_moc",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "anonymous": false,
    "inputs": [],
    "name": "ExecutedOnce",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [],
    "name": "PanicButtonRemoved",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "execute",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "moc",
    "outputs": [
      {
        "internalType": "contract IMoC",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608060405234801561000f575f80fd5b5060405161029a38038061029a83398101604081905261002e916100a0565b6001600160a01b03811661007c5760405162461bcd60e51b815260206004820152601160248201527057726f6e67204d6f43206164647265737360781b604482015260640160405180910390fd5b5f80546001600160a01b0319166001600160a01b03929092169190911790556100cd565b5f602082840312156100b0575f80fd5b81516001600160a01b03811681146100c6575f80fd5b9392505050565b6101c0806100da5f395ff3fe608060405234801561000f575f80fd5b5060043610610034575f3560e01c806353428253146100385780636146195414610066575b5f80fd5b5f5461004a906001600160a01b031681565b6040516001600160a01b03909116815260200160405180910390f35b61006e610070565b005b5f546001600160a01b03166100d55760405162461bcd60e51b815260206004820152602160248201527f54686973206368616e6765722077617320616c726561647920657865637574656044820152601960fa1b606482015260840160405180910390fd5b5f80546040805163148415c360e21b815290516001600160a01b0390921692635210570c9260048084019382900301818387803b158015610114575f80fd5b505af1158015610126573d5f803e3d5ffd5b50506040517f7afd4e1c5b47ebabaf6e296406a7039a93a197640cd9ba577d601d4f3f00c57e92505f9150a15f80546001600160a01b03191681556040517fcbb661e06b329753620d4e0fa4d22cb9c09fb080aeae80243bbc02044381a1999190a156fea264697066735822122083194bf477f0c93b04fc13ba40625b3f52ce2020c443265d7c783639d773351564736f6c63430008180033";

  
      type RemovePanicButtonProposalConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: RemovePanicButtonProposalConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class RemovePanicButtonProposal__factory extends ContractFactory {
    
      constructor(...args: RemovePanicButtonProposalConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(_moc: AddressLike, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(_moc, overrides || {});
    };
    override deploy(_moc: AddressLike, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(_moc, overrides || {}) as Promise<RemovePanicButtonProposal & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): RemovePanicButtonProposal__factory {
      return super.connect(runner) as RemovePanicButtonProposal__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): RemovePanicButtonProposalInterface {
      return new Interface(_abi) as RemovePanicButtonProposalInterface;
    }
    
    override attach(address: string | Addressable): RemovePanicButtonProposal {
      return super.attach(address) as RemovePanicButtonProposal;
    }
  static connect(address: string, runner?: ContractRunner | null): RemovePanicButtonProposal {
      return new Contract(address, _abi, runner) as unknown as RemovePanicButtonProposal;
    }
  }

  
  