/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IGovernorInterface extends Interface {
    getFunction(nameOrSignature: "executeChange" | "isAuthorizedChanger"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'executeChange', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isAuthorizedChanger', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'executeChange', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isAuthorizedChanger', data: BytesLike): Result;
  }

  

  export interface IGovernor extends BaseContract {
    
    connect(runner?: ContractRunner | null): IGovernor;
    waitForDeployment(): Promise<this>;

    interface: IGovernorInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    executeChange: TypedContractMethod<
      [changeContract_: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    isAuthorizedChanger: TypedContractMethod<
      [changer_: AddressLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'executeChange'): TypedContractMethod<
      [changeContract_: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isAuthorizedChanger'): TypedContractMethod<
      [changer_: AddressLike, ],
      [boolean],
      'view'
    >;

    

    filters: {
      
    };
  }