/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IMoCv2Interface extends Interface {
    getFunction(nameOrSignature: "feeTokenPct" | "mintTCandTPFee" | "redeemTCandTPFee" | "setFeeTokenPct" | "setMintTCandTPFee" | "setRedeemTCandTPFee" | "setSwapTCforTPFee" | "setSwapTPforTCFee" | "setSwapTPforTPFee" | "setTCInterestRate" | "setTcMintFee" | "setTcRedeemFee" | "swapTCforTPFee" | "swapTPforTCFee" | "swapTPforTPFee" | "tcInterestRate" | "tcMintFee" | "tcRedeemFee"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'feeTokenPct', values?: undefined): string;
encodeFunctionData(functionFragment: 'mintTCandTPFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'redeemTCandTPFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'setFeeTokenPct', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setMintTCandTPFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setRedeemTCandTPFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setSwapTCforTPFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setSwapTPforTCFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setSwapTPforTPFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTCInterestRate', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTcMintFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTcRedeemFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'swapTCforTPFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'swapTPforTCFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'swapTPforTPFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'tcInterestRate', values?: undefined): string;
encodeFunctionData(functionFragment: 'tcMintFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'tcRedeemFee', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'feeTokenPct', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintTCandTPFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'redeemTCandTPFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFeeTokenPct', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMintTCandTPFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRedeemTCandTPFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setSwapTCforTPFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setSwapTPforTCFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setSwapTPforTPFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTCInterestRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTcMintFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTcRedeemFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapTCforTPFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapTPforTCFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapTPforTPFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tcInterestRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tcMintFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tcRedeemFee', data: BytesLike): Result;
  }

  

  export interface IMoCv2 extends BaseContract {
    
    connect(runner?: ContractRunner | null): IMoCv2;
    waitForDeployment(): Promise<this>;

    interface: IMoCv2Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    feeTokenPct: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    mintTCandTPFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    redeemTCandTPFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    setFeeTokenPct: TypedContractMethod<
      [feeTokenPct_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setMintTCandTPFee: TypedContractMethod<
      [mintTCandTPFee_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setRedeemTCandTPFee: TypedContractMethod<
      [redeemTCandTPFee_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setSwapTCforTPFee: TypedContractMethod<
      [swapTCforTPFee_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setSwapTPforTCFee: TypedContractMethod<
      [swapTPforTCFee_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setSwapTPforTPFee: TypedContractMethod<
      [swapTPforTPFee_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setTCInterestRate: TypedContractMethod<
      [tcInterestRate_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setTcMintFee: TypedContractMethod<
      [tcMintFee_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setTcRedeemFee: TypedContractMethod<
      [tcRedeemFee_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    swapTCforTPFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    swapTPforTCFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    swapTPforTPFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    tcInterestRate: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    tcMintFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    tcRedeemFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'feeTokenPct'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'mintTCandTPFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'redeemTCandTPFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setFeeTokenPct'): TypedContractMethod<
      [feeTokenPct_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMintTCandTPFee'): TypedContractMethod<
      [mintTCandTPFee_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setRedeemTCandTPFee'): TypedContractMethod<
      [redeemTCandTPFee_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setSwapTCforTPFee'): TypedContractMethod<
      [swapTCforTPFee_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setSwapTPforTCFee'): TypedContractMethod<
      [swapTPforTCFee_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setSwapTPforTPFee'): TypedContractMethod<
      [swapTPforTPFee_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTCInterestRate'): TypedContractMethod<
      [tcInterestRate_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTcMintFee'): TypedContractMethod<
      [tcMintFee_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTcRedeemFee'): TypedContractMethod<
      [tcRedeemFee_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'swapTCforTPFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'swapTPforTCFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'swapTPforTPFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tcInterestRate'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tcMintFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tcRedeemFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }