/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IChangeContract } from './IChangeContract.js';
export type { IGovernor } from './IGovernor.js';
export type { IMoC } from './IMoC.js';
export type { IMoCInrate } from './IMoCInrate.js';
export type { IMoCv2 } from './IMoCv2.js';