/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as removePanicButtonProposalSol from './RemovePanicButtonProposal.sol/index.js';
export type { removePanicButtonProposalSol };