/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface RemovePanicButtonProposalInterface extends Interface {
    getFunction(nameOrSignature: "execute" | "moc"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ExecutedOnce" | "PanicButtonRemoved"): EventFragment;

    encodeFunctionData(functionFragment: 'execute', values?: undefined): string;
encodeFunctionData(functionFragment: 'moc', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'execute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'moc', data: BytesLike): Result;
  }

  
    export namespace ExecutedOnceEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PanicButtonRemovedEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface RemovePanicButtonProposal extends BaseContract {
    
    connect(runner?: ContractRunner | null): RemovePanicButtonProposal;
    waitForDeployment(): Promise<this>;

    interface: RemovePanicButtonProposalInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    execute: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    moc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'execute'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'moc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'ExecutedOnce'): TypedContractEvent<ExecutedOnceEvent.InputTuple, ExecutedOnceEvent.OutputTuple, ExecutedOnceEvent.OutputObject>;
getEvent(key: 'PanicButtonRemoved'): TypedContractEvent<PanicButtonRemovedEvent.InputTuple, PanicButtonRemovedEvent.OutputTuple, PanicButtonRemovedEvent.OutputObject>;

    filters: {
      
      'ExecutedOnce()': TypedContractEvent<ExecutedOnceEvent.InputTuple, ExecutedOnceEvent.OutputTuple, ExecutedOnceEvent.OutputObject>;
      ExecutedOnce: TypedContractEvent<ExecutedOnceEvent.InputTuple, ExecutedOnceEvent.OutputTuple, ExecutedOnceEvent.OutputObject>;
    

      'PanicButtonRemoved()': TypedContractEvent<PanicButtonRemovedEvent.InputTuple, PanicButtonRemovedEvent.OutputTuple, PanicButtonRemovedEvent.OutputObject>;
      PanicButtonRemoved: TypedContractEvent<PanicButtonRemovedEvent.InputTuple, PanicButtonRemovedEvent.OutputTuple, PanicButtonRemovedEvent.OutputObject>;
    
    };
  }