/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { MocHelper, MocHelperInterface } from "../../utils/MocHelper.js";

  const _abi = [
  {
    "inputs": [],
    "name": "InvalidAddress",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidValue",
    "type": "error"
  }
] as const;

  export class MocHelper__factory {
    static readonly abi = _abi;
    static createInterface(): MocHelperInterface {
      return new Interface(_abi) as MocHelperInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): MocHelper {
      return new Contract(address, _abi, runner) as unknown as MocHelper;
    }
  }
  