/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { MoCInrateMock, MoCInrateMockInterface } from "../../mocks/MoCInrateMock.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "newRate",
        "type": "uint256"
      }
    ],
    "name": "BitProRateSet",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint8",
        "name": "txType",
        "type": "uint8"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "fee",
        "type": "uint256"
      }
    ],
    "name": "CommissionRateSet",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "bitProRate",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "name": "commissionByTxType",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "newBitProRate",
        "type": "uint256"
      }
    ],
    "name": "setBitProRate",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "txType",
        "type": "uint8"
      },
      {
        "internalType": "uint256",
        "name": "value",
        "type": "uint256"
      }
    ],
    "name": "setCommissionRateByTxType",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608060405234801561000f575f80fd5b506101e58061001d5f395ff3fe608060405234801561000f575f80fd5b506004361061004a575f3560e01c80636c2b7b7e1461004e57806379f8a7a5146100685780637aba8a1a1461007d578063bcbe0a351461009c575b5f80fd5b6100565f5481565b60405190815260200160405180910390f35b61007b61007636600461013b565b6100af565b005b61005661008b366004610167565b60016020525f908152604090205481565b61007b6100aa366004610187565b6100e9565b5f8190556040518181527fb781adf72a8f53bede29309d2b217e8184549dc7629d6db57341d0b642758f7b9060200160405180910390a150565b60ff82165f8181526001602052604090819020839055517f4ca8ffa5e68df889afb8aea95038451f922828ce2e9e99f4272727431269779c9061012f9084815260200190565b60405180910390a25050565b5f6020828403121561014b575f80fd5b5035919050565b803560ff81168114610162575f80fd5b919050565b5f60208284031215610177575f80fd5b61018082610152565b9392505050565b5f8060408385031215610198575f80fd5b6101a183610152565b94602093909301359350505056fea26469706673582212201361a1a3e51bde19ddfda402d24e341d11d4adaacb45ca9a5d5ee249013ec65864736f6c63430008180033";

  
      type MoCInrateMockConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MoCInrateMockConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MoCInrateMock__factory extends ContractFactory {
    
      constructor(...args: MoCInrateMockConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MoCInrateMock & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MoCInrateMock__factory {
      return super.connect(runner) as MoCInrateMock__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MoCInrateMockInterface {
      return new Interface(_abi) as MoCInrateMockInterface;
    }
    
    override attach(address: string | Addressable): MoCInrateMock {
      return super.attach(address) as MoCInrateMock;
    }
  static connect(address: string, runner?: ContractRunner | null): MoCInrateMock {
      return new Contract(address, _abi, runner) as unknown as MoCInrateMock;
    }
  }

  
  