/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { MockGovernor, MockGovernorInterface } from "../../mocks/MockGovernor.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "authorized",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "changer",
        "type": "address"
      }
    ],
    "name": "isAuthorized",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "changer",
        "type": "address"
      }
    ],
    "name": "isAuthorizedChanger",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "changer",
        "type": "address"
      },
      {
        "internalType": "bool",
        "name": "isAuth",
        "type": "bool"
      }
    ],
    "name": "setAuthorized",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608060405234801561000f575f80fd5b506101938061001d5f395ff3fe608060405234801561000f575f80fd5b506004361061004a575f3560e01c8063711bf9b21461004e578063b918161114610088578063d994d6d5146100be578063fe9fbb80146100be575b5f80fd5b61008661005c366004610104565b6001600160a01b03919091165f908152602081905260409020805460ff1916911515919091179055565b005b6100aa61009636600461013d565b5f6020819052908152604090205460ff1681565b604051901515815260200160405180910390f35b6100aa6100cc36600461013d565b6001600160a01b03165f9081526020819052604090205460ff1690565b80356001600160a01b03811681146100ff575f80fd5b919050565b5f8060408385031215610115575f80fd5b61011e836100e9565b915060208301358015158114610132575f80fd5b809150509250929050565b5f6020828403121561014d575f80fd5b610156826100e9565b939250505056fea2646970667358221220b65fb49bf1870bd5b4db3cc2d0fa58012d6a690e9364f7efddf431134505722764736f6c63430008180033";

  
      type MockGovernorConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockGovernorConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockGovernor__factory extends ContractFactory {
    
      constructor(...args: MockGovernorConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MockGovernor & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockGovernor__factory {
      return super.connect(runner) as MockGovernor__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockGovernorInterface {
      return new Interface(_abi) as MockGovernorInterface;
    }
    
    override attach(address: string | Addressable): MockGovernor {
      return super.attach(address) as MockGovernor;
    }
  static connect(address: string, runner?: ContractRunner | null): MockGovernor {
      return new Contract(address, _abi, runner) as unknown as MockGovernor;
    }
  }

  
  