/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { MoCMock, MoCMockInterface } from "../../mocks/MoCMock.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [],
    "name": "MadeUnstoppable",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "makeUnstoppable",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "unstoppable",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f80fd5b5060c68061001b5f395ff3fe6080604052348015600e575f80fd5b50600436106030575f3560e01c80635210570c1460345780639ec02f6a14603c575b5f80fd5b603a605b565b005b5f5460479060ff1681565b604051901515815260200160405180910390f35b5f805460ff191660011781556040517f8dcfaffc409db8e2854889cfda3d4707b537852457f5ee97f6e32f3cc8351ba89190a156fea26469706673582212206f349303e61736dacbc5eb3038822cbe2930d19245c1c7aaf5dda5e59ee0bf9a64736f6c63430008180033";

  
      type MoCMockConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MoCMockConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MoCMock__factory extends ContractFactory {
    
      constructor(...args: MoCMockConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MoCMock & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MoCMock__factory {
      return super.connect(runner) as MoCMock__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MoCMockInterface {
      return new Interface(_abi) as MoCMockInterface;
    }
    
    override attach(address: string | Addressable): MoCMock {
      return super.attach(address) as MoCMock;
    }
  static connect(address: string, runner?: ContractRunner | null): MoCMock {
      return new Contract(address, _abi, runner) as unknown as MoCMock;
    }
  }

  
  