/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../../common.js"
  

  export interface IMoCInrateMinimalInterface extends Interface {
    getFunction(nameOrSignature: "setBitProRate" | "setCommissionRateByTxType"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'setBitProRate', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setCommissionRateByTxType', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'setBitProRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setCommissionRateByTxType', data: BytesLike): Result;
  }

  

  export interface IMoCInrateMinimal extends BaseContract {
    
    connect(runner?: ContractRunner | null): IMoCInrateMinimal;
    waitForDeployment(): Promise<this>;

    interface: IMoCInrateMinimalInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    setBitProRate: TypedContractMethod<
      [newBitProRate: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setCommissionRateByTxType: TypedContractMethod<
      [txType: BigNumberish, value: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'setBitProRate'): TypedContractMethod<
      [newBitProRate: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setCommissionRateByTxType'): TypedContractMethod<
      [txType: BigNumberish, value: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }