/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMoCInrateMinimal } from './IMoCInrateMinimal.js';
export type { IMoCMinimal } from './IMoCMinimal.js';
export type { RemovePanicButtonProposal } from './RemovePanicButtonProposal.js';